# mongo_groups_count   = 10
mongo_gateways_enable = false
mongo_servers_enable = false
mongo_groups_count   = 10
mongo_replicas_count = 1
ssh_private_key      = "~/.ssh/keyring.syntaxio/francaise-des-jeux/id_ed25519"
ssh_public_key       = "~/.ssh/keyring.syntaxio/francaise-des-jeux/id_ed25519.pub"
domain_name          = "glenux.net"
subdomain_suffix     = "teaching"
