---

- name: "Sync time - first try (needed by apt)"
  ansible.builtin.shell:
    cmd: hash ntpdate 2>/dev/null && ntpdate 0.debian.pool.ntp.org
  ignore_errors: 'yes'
  no_log: 'yes'

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - vim
      - ntpdate
    state: latest
    update_cache: true

- name: "Sync time - for real (needed by sshwifty)"
  ansible.builtin.command:
    cmd: ntpdate 0.debian.pool.ntp.org

#
